---

name:
    {{name}}
version:
    0.1.0.0
github:
    {{github-username}}{{^github-username}}githubuser{{/github-username}}/{{name}}
homepage:
    https://github.com/{{github-username}}{{^github-username}}githubuser{{/github-username}}/{{name}}#readme
license:
    BSD3
license-file:
    LICENSE
author:
    {{author-name}}{{^author-name}}Author name here{{/author-name}}
maintainer:
    {{author-email}}{{^author-email}}example@example.com{{/author-email}}
copyright:
    {{copyright}}{{^copyright}}{{year}}{{^year}}2020{{/year}} {{author-name}}{{^author-name}}Author name here{{/author-name}}{{/copyright}}
category:
    {{category}}{{^category}}Web{{/category}}
extra-source-files:
    - README.md
    - CHANGELOG.md


synopsis:
    Short, one-line summary of project here.

description: |
    Longer description of package here.

    Maybe include a simple usage example.


ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints
    - -O2

default-extensions:
    - DeriveGeneric
    - LambdaCase
    - NamedFieldPuns
    - OverloadedStrings
    - TupleSections
    - TypeApplications
    - TypeOperators
    - ViewPatterns


dependencies:
    - base >= 4.7 && < 5


library:
    source-dirs:
        src
    dependencies:
        []

executables:
    {{name}}:
        source-dirs:
            app
        main:
            Main.hs
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts "-N -T"
        dependencies:
            - {{name}}

tests:
    {{name}}-test:
        main: Spec.hs
        source-dirs:
            tests
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts "-N -T"
        dependencies:
            - {{name}}
            - hedgehog
            - tasty
            - tasty-hedgehog
            - tasty-hunit
