---

name:
    {{name}}
version:
    0.1.0.0
github:
    {{github-username}}{{^github-username}}githubuser{{/github-username}}/{{name}}
homepage:
    https://github.com/{{github-username}}{{^github-username}}githubuser{{/github-username}}/{{name}}#readme
license:
    BSD3
license-file:
    LICENSE
author:
    {{author-name}}{{^author-name}}Author name here{{/author-name}}
maintainer:
    {{author-email}}{{^author-email}}example@example.com{{/author-email}}
copyright:
    {{copyright}}{{^copyright}}{{year}}{{^year}}2020{{/year}} {{author-name}}{{^author-name}}Author name here{{/author-name}}{{/copyright}}
category:
    {{category}}{{^category}}Web{{/category}}
extra-source-files:
    - README.md
    - CHANGELOG.md


synopsis:
    Short, one-line summary of project here.

description: |
    Longer description of package here.

    Maybe include a simple usage example.


ghc-options:
    - -Wall
when:
    condition:
        impl(ghc >= 8.0)
    then:
        ghc-options:
            - -Wcompat
            - -Wincomplete-record-updates
            - -Wincomplete-uni-patterns
            - -Wredundant-constraints
    else:
        ghc-options:
            - -fwarn-incomplete-record-updates
            - -fwarn-incomplete-uni-patterns


dependencies:
    - base >= 4.3 && < 5
    - base-compat-batteries


library:
    source-dirs:
        src
    dependencies:
        []

tests:
    {{name}}-test:
        main: Spec.hs
        source-dirs:
            tests
        ghc-options:
            - -threaded
            - -rtsopts
            - -with-rtsopts "-N -T"
        dependencies:
            - {{name}}
            - hedgehog
            - tasty
            - tasty-hedgehog
            - tasty-hunit
